# Generated by Django 4.2 on 2026-04-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('warden_name', models.CharField(blank=True, max_length=100)),
                ('warden_phone', models.CharField(blank=True, max_length=20)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dormitory',
                'verbose_name_plural': 'Dormitories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('dormitory', 'Dormitory')], max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('total_beds', models.PositiveIntegerField(default=1)),
                ('cost_per_bed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dormitory.dormitory')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'unique_together': {('dormitory', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='dormitory.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Room',
                'verbose_name_plural': 'Student Rooms',
            },
        ),
    ]
