# Generated by Django 4.2 on 2026-04-14 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage type)', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount Category',
                'verbose_name_plural': 'Discount Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_groups', to='students.academicyear')),
            ],
            options={
                'verbose_name': 'Fee Group',
                'verbose_name_plural': 'Fee Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feecategory',
            name='category_type',
            field=models.CharField(choices=[('tuition', 'Tuition Fee'), ('annual', 'Annual Charges'), ('monthly', 'Monthly Charges'), ('one_time', 'One Time'), ('transport', 'Transport Fee'), ('exam', 'Examination Fee'), ('library', 'Library Fee'), ('laboratory', 'Laboratory Fee'), ('sports', 'Sports Fee'), ('other', 'Other')], default='tuition', max_length=20),
        ),
        migrations.CreateModel(
            name='FeeParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='one_time', max_length=20)),
                ('is_optional', models.BooleanField(default=False, help_text='Students can opt out of this fee')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='finance.feecategory')),
            ],
            options={
                'verbose_name': 'Fee Particular',
                'verbose_name_plural': 'Fee Particulars',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeGroupParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Override the default amount (optional)', max_digits=10, null=True)),
                ('fee_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feegroup')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feeparticular')),
            ],
            options={
                'unique_together': {('fee_group', 'particular')},
            },
        ),
        migrations.AddField(
            model_name='feegroup',
            name='particulars',
            field=models.ManyToManyField(related_name='fee_groups', through='finance.FeeGroupParticular', to='finance.feeparticular'),
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discounts', to='finance.discountcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Discount',
                'verbose_name_plural': 'Student Discounts',
                'unique_together': {('student', 'discount_category')},
            },
        ),
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override total fee amount', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='students.class')),
                ('fee_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='finance.feegroup')),
            ],
            options={
                'verbose_name': 'Class Fee',
                'verbose_name_plural': 'Class Fees',
                'ordering': ['assigned_class__name'],
                'unique_together': {('assigned_class', 'fee_group')},
            },
        ),
    ]
