# Generated by Django 4.2 on 2026-04-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('receptionist', 'Receptionist'), ('driver', 'Driver'), ('cook', 'Cook'), ('guard', 'Security Guard'), ('cleaner', 'Cleaner'), ('maintenance', 'Maintenance'), ('counselor', 'Counselor'), ('nurse', 'School Nurse')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-time'), ('temporary', 'Temporary')], default='permanent', max_length=20)),
                ('shift_timing', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
