# Generated by Django 4.2 on 2026-04-14 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_absent_threshold', models.PositiveIntegerField(default=10, help_text='Days of consecutive absence before marking as auto-absent')),
                ('require_attendance_remark', models.BooleanField(default=False)),
                ('allow_attendance_edit', models.BooleanField(default=True)),
                ('attendance_edit_days_limit', models.PositiveIntegerField(default=7, help_text='Days limit for editing attendance (0 = no limit)')),
                ('attendance_percentage_required', models.PositiveIntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console (Development)'), ('django.core.mail.backends.filebased.EmailBackend', 'File (Development)')], default='django.core.mail.backends.smtp.EmailBackend', max_length=100)),
                ('email_host', models.CharField(blank=True, max_length=200)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.EmailField(blank=True, max_length=254)),
                ('email_host_password', models.CharField(blank=True, max_length=200)),
                ('email_from_name', models.CharField(default='School Management', max_length=100)),
                ('email_from_address', models.EmailField(blank=True, max_length=254)),
                ('email_signature', models.TextField(blank=True)),
                ('test_email_recipient', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_partial_payment', models.BooleanField(default=True)),
                ('partial_payment_type', models.CharField(choices=[('percentage', 'Percentage Based'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('partial_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_enabled', models.BooleanField(default=False)),
                ('late_fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_after_days', models.PositiveIntegerField(default=7)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('due_warning_days', models.PositiveIntegerField(default=3)),
                ('auto_reminder', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Settings',
                'verbose_name_plural': 'Fee Settings',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(default='Y-m-d', max_length=20)),
                ('time_format', models.CharField(default='H:i', max_length=20)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US)'), ('America/Chicago', 'Central Time (US)'), ('America/Denver', 'Mountain Time (US)'), ('America/Los_Angeles', 'Pacific Time (US)'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Asia/Dubai', 'Dubai'), ('Asia/Kolkata', 'India'), ('Asia/Dhaka', 'Bangladesh'), ('Asia/Karachi', 'Pakistan'), ('Asia/Singapore', 'Singapore'), ('Africa/Lagos', 'Lagos'), ('Africa/Johannesburg', 'Johannesburg')], default='UTC', max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('PKR', 'Pakistani Rupee'), ('BDT', 'Bangladeshi Taka'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('ZAR', 'South African Rand'), ('PHP', 'Philippine Peso'), ('MYR', 'Malaysian Ringgit'), ('SGD', 'Singapore Dollar')], default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('decimal_places', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('working_days', models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', max_length=50)),
                ('class_duration', models.PositiveIntegerField(default=45, help_text='Duration in minutes')),
                ('break_duration', models.PositiveIntegerField(default=15, help_text='Break duration in minutes')),
                ('school_start_time', models.TimeField(default='08:00')),
                ('school_end_time', models.TimeField(default='15:00')),
                ('require_student_photo', models.BooleanField(default=True)),
                ('require_guardian_info', models.BooleanField(default=True)),
                ('auto_assign_roll_number', models.BooleanField(default=True)),
                ('student_id_prefix', models.CharField(default='STU', max_length=10)),
                ('teacher_id_prefix', models.CharField(default='TCH', max_length=10)),
                ('staff_id_prefix', models.CharField(default='STF', max_length=10)),
                ('academic_year_start_month', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_parent_portal', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='ResultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_system', models.CharField(choices=[('percentage', 'Percentage Based'), ('grade', 'Grade Based'), ('gpa', 'GPA Based'), ('cwa', 'CWA Based')], default='percentage', max_length=20)),
                ('publish_result', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('require_attendance_for_result', models.BooleanField(default=False)),
                ('allow_rank', models.BooleanField(default=True)),
                ('show_pass_fail', models.BooleanField(default=True)),
                ('show_grade', models.BooleanField(default=True)),
                ('show_percentage', models.BooleanField(default=True)),
                ('show_remarks', models.BooleanField(default=True)),
                ('decimal_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
            options={
                'verbose_name': 'Result Settings',
                'verbose_name_plural': 'Result Settings',
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My School', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='school/favicon/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', max_length=20)),
                ('layout', models.CharField(choices=[('sidebar', 'Sidebar (Traditional)'), ('collapsed', 'Collapsed Sidebar'), ('horizontal', 'Horizontal Menu')], default='sidebar', max_length=20)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('sidebar_color', models.CharField(default='#1e1e2d', max_length=20)),
                ('compact_mode', models.BooleanField(default=False)),
                ('box_shadow', models.BooleanField(default=True)),
                ('border_radius', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
