# Generated by Django 4.2 on 2026-04-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_roles',
            field=models.CharField(blank=True, default='all', max_length=200),
        ),
    ]
